//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupermarketTuto.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseTbl
    {
        public int PurchaseId { get; set; }
        public int ProdId { get; set; }
        public int Catd { get; set; }
        public int BillId { get; set; }
        public int SellerId { get; set; }
    
        public virtual BillTbl BillTbl { get; set; }
        public virtual CategoryTbl CategoryTbl { get; set; }
        public virtual ProductTbl ProductTbl { get; set; }
        public virtual SellerTbl SellerTbl { get; set; }
    }
}
