//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupermarketTuto.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class SellerTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SellerTbl()
        {
            this.PurchaseTbls = new HashSet<PurchaseTbl>();
        }
    
        public int SellerId { get; set; }
        public string SellerName { get; set; }
        public int SellerAge { get; set; }
        public int SellePhone { get; set; }
        public string SellerPass { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseTbl> PurchaseTbls { get; set; }
    }
}
